/*
 * Copyright 2019 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
#pragma once

#ifdef LAGRANGE_ENABLE_LEGACY_FUNCTIONS
    #include <lagrange/primitive/legacy/generate_torus.h>
#endif

#include <lagrange/SurfaceMesh.h>
#include <lagrange/internal/constants.h>
#include <lagrange/primitive/PrimitiveOptions.h>

namespace lagrange::primitive {

/// @addtogroup module-primitive
/// @{

///
/// Options for generating a torus mesh.
///
struct TorusOptions : public PrimitiveOptions
{
    using Scalar = PrimitiveOptions::Scalar;
    using Index = size_t;

    /// Distance from the center of the torus to the center of the tube (donut hole to tube center).
    /// This defines the overall size of the torus.
    Scalar major_radius = 5;

    /// Radius of the tube that forms the torus (thickness of the donut).
    /// Must be smaller than or equal to major_radius.
    Scalar minor_radius = 1;

    /// Number of subdivisions around the major circumference (around the donut hole).
    /// Higher values create smoother circular cross-sections around the main ring.
    Index ring_segments = 50;

    /// Number of subdivisions around the minor circumference (around the tube).
    /// Higher values create smoother circular cross-sections of the tube itself.
    Index pipe_segments = 50;

    /// Starting angle for partial torus generation (in radians).
    /// 0 corresponds to the positive X-axis.
    Scalar start_sweep_angle = 0;

    /// Ending angle for partial torus generation (in radians).
    /// Default of 2π creates a full torus.
    Scalar end_sweep_angle = static_cast<Scalar>(2 * lagrange::internal::pi);

    ///
    /// Clamps all parameters to valid ranges.
    ///
    /// This method ensures that:
    /// - minor_radius is non-negative
    /// - major_radius is at least as large as minor_radius
    /// - Both ring_segments and pipe_segments are at least 3 (minimum for closed shapes)
    ///
    /// The constraint major_radius >= minor_radius prevents invalid torus geometries
    /// where the tube would be larger than the overall torus structure.
    ///
    void project_to_valid_range()
    {
        minor_radius = std::max(minor_radius, static_cast<Scalar>(0.0));
        major_radius = std::max(major_radius, static_cast<Scalar>(minor_radius));
        ring_segments = std::max(ring_segments, static_cast<Index>(3));
        pipe_segments = std::max(pipe_segments, static_cast<Index>(3));
    }
};

///
/// Generate a torus mesh.
///
/// Creates a torus (donut-shaped) mesh with the specified parameters. The torus is centered
/// at setting.center with its center ring parallel to the XZ plane.
///
/// Partial tori can be generated by specifying start_sweep_angle and end_sweep_angle
/// different from 0 and 2π respectively.
///
/// @tparam Scalar  The scalar type for vertex coordinates
/// @tparam Index   The index type for face indices
///
/// @param setting  Configuration parameters for the torus generation
///
/// @return A surface mesh representing the torus
///
/// @note The function automatically calls setting.project_to_valid_range() to ensure
///       all parameters are within valid bounds before generation.
///
template <typename Scalar, typename Index>
SurfaceMesh<Scalar, Index> generate_torus(TorusOptions setting);

/// @}

} // namespace lagrange::primitive
