#
# Copyright 2026 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# Emit bindings/js/src/generated/registry.ts listing every module that registered via
# lagrange_add_js_binding(). Defined in root scope so cmake_language(DEFER CALL ...) can
# find it when firing at end of top-level directory processing.
function(lagrange_js_emit_registry)
    get_property(_modules GLOBAL PROPERTY LAGRANGE_JS_REGISTRY)
    if(NOT _modules)
        return()
    endif()
    list(REMOVE_DUPLICATES _modules)
    list(SORT _modules)

    get_property(_src_dir GLOBAL PROPERTY __lagrange_source_dir)
    set(_out "${_src_dir}/bindings/js/src/generated/registry.ts")

    set(_content "// GENERATED FILE — do not edit. Regenerated by CMake (lagrange_js_emit_registry).\n")
    string(APPEND _content "// One entry per modules/<name>/js/ts/<stem>.ts that was compiled into this build.\n\n")

    foreach(_m IN LISTS _modules)
        string(APPEND _content "export * from \"../modules/${_m}.js\";\n")
    endforeach()
    string(APPEND _content "\n")

    foreach(_m IN LISTS _modules)
        get_property(_type GLOBAL PROPERTY LAGRANGE_JS_REGISTRY_TYPE_${_m})
        string(APPEND _content "import type { ${_type} } from \"../modules/${_m}.js\";\n")
        string(APPEND _content "import { ${_m}ModuleKeys } from \"../modules/${_m}.js\";\n")
    endforeach()
    string(APPEND _content "\n")

    string(APPEND _content "export interface Lagrange {\n")
    foreach(_m IN LISTS _modules)
        get_property(_type GLOBAL PROPERTY LAGRANGE_JS_REGISTRY_TYPE_${_m})
        string(APPEND _content "  ${_m}: ${_type};\n")
    endforeach()
    string(APPEND _content "}\n\n")

    string(APPEND _content "export const moduleRegistry = {\n")
    foreach(_m IN LISTS _modules)
        string(APPEND _content "  ${_m}: ${_m}ModuleKeys,\n")
    endforeach()
    string(APPEND _content "} as const;\n")

    set(_existing "")
    if(EXISTS "${_out}")
        file(READ "${_out}" _existing)
    endif()
    if(NOT "${_existing}" STREQUAL "${_content}")
        file(WRITE "${_out}" "${_content}")
        list(LENGTH _modules _count)
        message(STATUS "lagrange_js: wrote ${_out} (${_count} modules)")
    endif()
endfunction()
